### ISSUE TITLE
when Test policies with 1000 test cases.During the training, the dimension is set to 128, and the test instruction is also set to 128

### ISSUE THREAD

**Issue by wyf08130** [GDam90/hyp2nav#1]
python test.py --model_dir data/model_name --hyperbolic --embedding_dimension 128 --gpu --device cuda:0
embedding_dimension 128
Traceback (most recent call last):
  File "test.py", line 404, in <module>
    main(sys_args)
  File "test.py", line 96, in main
    policy.load_model(model_weights)
  File "/home/wyfjyc/hyp2nav/crowd_nav/policy/tree_searchrl.py", line 217, in load_model
    self.load_state_dict(checkpoint)
  File "/home/wyfjyc/hyp2nav/crowd_nav/policy/tree_searchrl.py", line 206, in load_state_dict
    self.value_estimator.value_network.load_state_dict(state_dict['value_network'])
  File "/home/wyfjyc/anaconda3/envs/hyp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for HyperDuelingDQN:
        Missing key(s) in state_dict: "feauture_layer.1.weight", "feauture_layer.1.bias". 
        Unexpected key(s) in state_dict: "feauture_layer.2.weight", "feauture_layer.2.bias". 
        size mismatch for feauture_layer.0.weight: copying a param with shape torch.Size([128, 32]) from checkpoint, the shape in current model is torch.Size([32, 32]).
        size mismatch for feauture_layer.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for value_stream.0.weight: copying a param with shape torch.Size([128, 128]) from checkpoint, the shape in current model is torch.Size([32, 128]).
        size mismatch for value_stream.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for value_stream.2.weight: copying a param with shape torch.Size([1, 128]) from checkpoint, the shape in current model is torch.Size([1, 32]).
        size mismatch for advantage_stream.0.weight: copying a param with shape torch.Size([128, 128]) from checkpoint, the shape in current model is torch.Size([32, 128]).
        size mismatch for advantage_stream.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for advantage_stream.2.weight: copying a param with shape torch.Size([81, 128]) from checkpoint, the shape in current model is torch.Size([81, 32]).

**Comment by GDam90** [comment]
Hi @wyf08130 ,

Thank you for your interest and for pointing out this problem, and sorry for the late reply. 

We have noticed that there is an error in the readME: the command to launch the train does not have the `--hyperbolic` flag, which is necessary to train hyp2nav.

We will correct the error in the readME right away, and please try running the `crowd_nav/train.py` script with the following command:

```
python train.py --policy tree-search-rl --output_dir data/model_name/ --config configs/icra_benchmark/ts_HVNet_Hypercuriosity.py --gpu --wandb_mode online --wandb_name name_of_the_run --embedding_dimension=128 --hyperbolic
```
